# Generated by Django 5.2.6 on 2025-09-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicl", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="artist",
            field=models.CharField(
                blank=True, default="Unknown Artist", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="title",
            field=models.CharField(blank=True, default="Unknown Title", max_length=200),
        ),
    ]
