# Generated by Django 5.2.6 on 2025-09-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicl", "0002_alter_track_artist_alter_track_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="artist",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="track",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
